// Copyright 2024 Karpeles Lab Inc.
//
// Verifies the MinLZ block decoder against vectors produced by the reference
// encoder (github.com/minio/minlz). The fixture is generated by the Go program
// in the project's development tooling and committed so CI needs no Go.
//
// Fixture format (little-endian); see the generator for the authoritative spec:
//   [u32 "MZTV"][u32 inputCount]
//   per input: [u32 nameLen][name][u32 origLen][orig][u8 variantCount]
//     per variant: [i8 level][u32 compLen][comp]

#![cfg(feature = "minlz")]

use minlz::minlz::{decompress, decompressed_len};

struct Cursor<'a> {
    b: &'a [u8],
    p: usize,
}

impl<'a> Cursor<'a> {
    fn u8(&mut self) -> u8 {
        let v = self.b[self.p];
        self.p += 1;
        v
    }
    fn u32(&mut self) -> usize {
        let v = u32::from_le_bytes(self.b[self.p..self.p + 4].try_into().unwrap());
        self.p += 4;
        v as usize
    }
    fn take(&mut self, n: usize) -> &'a [u8] {
        let s = &self.b[self.p..self.p + n];
        self.p += n;
        s
    }
}

#[test]
fn decode_reference_vectors() {
    let data = include_bytes!("fixtures/minlz_blocks.bin");
    let mut c = Cursor { b: data, p: 0 };
    assert_eq!(c.take(4), b"MZTV", "bad fixture magic");

    let inputs = c.u32();
    let mut variants = 0usize;
    for _ in 0..inputs {
        let name_len = c.u32();
        let name = core::str::from_utf8(c.take(name_len)).unwrap().to_string();
        let orig_len = c.u32();
        let orig = c.take(orig_len).to_vec();
        let nvar = c.u8();
        for _ in 0..nvar {
            let level = c.u8() as i8;
            let comp_len = c.u32();
            let comp = c.take(comp_len);

            let dl = decompressed_len(comp)
                .unwrap_or_else(|e| panic!("{name} l{level}: decompressed_len: {e:?}"));
            assert_eq!(dl, orig.len(), "{name} l{level}: decompressed_len mismatch");

            let got =
                decompress(comp).unwrap_or_else(|e| panic!("{name} l{level}: decompress: {e:?}"));
            assert_eq!(got, orig, "{name} l{level}: decoded bytes mismatch");
            variants += 1;
        }
    }
    assert!(variants >= 30, "expected many vectors, got {variants}");
    eprintln!("verified {variants} reference vectors across {inputs} inputs");
}
